//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estancionamento.segurancaWEB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ehsolucoes.com.br/webService/", ConfigurationName="segurancaWEB.segurancaSoap")]
    public interface segurancaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/iValorSeguranca", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int iValorSeguranca();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/iSomaSeguranca", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int iSomaSeguranca();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/sCriptografarString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sCriptografarString(string sTexto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/sDescriptografarString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sDescriptografarString(string sTexto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/sSenhaDireta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sSenhaDireta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/verificarDataExpiracao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool verificarDataExpiracao(string sLicenca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/verificarQteAcessosCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool verificarQteAcessosCliente(string sLicenca, int iQteAcessos, byte bTipo, string sIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/getCodigoCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int getCodigoCliente(string sLicenca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/getCodigoSistema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int getCodigoSistema(string sLicenca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/ativarComputador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ativarComputador(out string sAtivacao, string sLicenca, string sNumHD, string sNomeMaquina, System.DateTime dtDataAtual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/gerarContraChaveAtivacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string gerarContraChaveAtivacao(string sChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/validarChaveAtivacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool validarChaveAtivacao(string sChave, string sLicenca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/gerarChaveTela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string gerarChaveTela(System.DateTime dtAgora, string sLicenca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/gerarContraChaveTela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string gerarContraChaveTela(string sChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/validarChave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool validarChave(string sChave, string sContraChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/sFunctionTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sFunctionTest(string sTexto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ehsolucoes.com.br/webService/retornaDadosLicenca", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Estancionamento.segurancaWEB.licenciamento retornaDadosLicenca(string sLicenca);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ehsolucoes.com.br/webService/")]
    public partial class licenciamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int iDataExpiracaoField;
        
        private int iQteLicencasField;
        
        private int iCodClienteField;
        
        private int iCodSistemaField;
        
        private int iQteAcessosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iDataExpiracao {
            get {
                return this.iDataExpiracaoField;
            }
            set {
                this.iDataExpiracaoField = value;
                this.RaisePropertyChanged("iDataExpiracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int iQteLicencas {
            get {
                return this.iQteLicencasField;
            }
            set {
                this.iQteLicencasField = value;
                this.RaisePropertyChanged("iQteLicencas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int iCodCliente {
            get {
                return this.iCodClienteField;
            }
            set {
                this.iCodClienteField = value;
                this.RaisePropertyChanged("iCodCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int iCodSistema {
            get {
                return this.iCodSistemaField;
            }
            set {
                this.iCodSistemaField = value;
                this.RaisePropertyChanged("iCodSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int iQteAcessos {
            get {
                return this.iQteAcessosField;
            }
            set {
                this.iQteAcessosField = value;
                this.RaisePropertyChanged("iQteAcessos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface segurancaSoapChannel : Estancionamento.segurancaWEB.segurancaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class segurancaSoapClient : System.ServiceModel.ClientBase<Estancionamento.segurancaWEB.segurancaSoap>, Estancionamento.segurancaWEB.segurancaSoap {
        
        public segurancaSoapClient() {
        }
        
        public segurancaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public segurancaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public segurancaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public segurancaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int iValorSeguranca() {
            return base.Channel.iValorSeguranca();
        }
        
        public int iSomaSeguranca() {
            return base.Channel.iSomaSeguranca();
        }
        
        public string sCriptografarString(string sTexto) {
            return base.Channel.sCriptografarString(sTexto);
        }
        
        public string sDescriptografarString(string sTexto) {
            return base.Channel.sDescriptografarString(sTexto);
        }
        
        public string sSenhaDireta() {
            return base.Channel.sSenhaDireta();
        }
        
        public bool verificarDataExpiracao(string sLicenca) {
            return base.Channel.verificarDataExpiracao(sLicenca);
        }
        
        public bool verificarQteAcessosCliente(string sLicenca, int iQteAcessos, byte bTipo, string sIP) {
            return base.Channel.verificarQteAcessosCliente(sLicenca, iQteAcessos, bTipo, sIP);
        }
        
        public int getCodigoCliente(string sLicenca) {
            return base.Channel.getCodigoCliente(sLicenca);
        }
        
        public int getCodigoSistema(string sLicenca) {
            return base.Channel.getCodigoSistema(sLicenca);
        }
        
        public bool ativarComputador(out string sAtivacao, string sLicenca, string sNumHD, string sNomeMaquina, System.DateTime dtDataAtual) {
            return base.Channel.ativarComputador(out sAtivacao, sLicenca, sNumHD, sNomeMaquina, dtDataAtual);
        }
        
        public string gerarContraChaveAtivacao(string sChave) {
            return base.Channel.gerarContraChaveAtivacao(sChave);
        }
        
        public bool validarChaveAtivacao(string sChave, string sLicenca) {
            return base.Channel.validarChaveAtivacao(sChave, sLicenca);
        }
        
        public string gerarChaveTela(System.DateTime dtAgora, string sLicenca) {
            return base.Channel.gerarChaveTela(dtAgora, sLicenca);
        }
        
        public string gerarContraChaveTela(string sChave) {
            return base.Channel.gerarContraChaveTela(sChave);
        }
        
        public bool validarChave(string sChave, string sContraChave) {
            return base.Channel.validarChave(sChave, sContraChave);
        }
        
        public string sFunctionTest(string sTexto) {
            return base.Channel.sFunctionTest(sTexto);
        }
        
        public Estancionamento.segurancaWEB.licenciamento retornaDadosLicenca(string sLicenca) {
            return base.Channel.retornaDadosLicenca(sLicenca);
        }
    }
}
